/***
*** Interface: ads2002 2.2.0.0
 *** created by: admsXml-2.3.0 - Sun, 28 Feb 2010 22:28:36 ***/


#include "ngspice.h"
#include "devdefs.h"
#include "hicum2defs.h"
#include "suffix.h"
IFparm hicum2pTable[] = {

};
IFparm hicum2mPTable[] = {
 IOP("pnp",hicum2_model_pnp,IF_INTEGER,"pnp"),
 IOP("npn",hicum2_model_npn,IF_INTEGER,"npn"),
 IOP("c10",hicum2_model_c10,IF_REAL,"c10"),
 IOP("qp0",hicum2_model_qp0,IF_REAL,"qp0"),
 IOP("ich",hicum2_model_ich,IF_REAL,"ich"),
 IOP("hfe",hicum2_model_hfe,IF_REAL,"hfe"),
 IOP("hfc",hicum2_model_hfc,IF_REAL,"hfc"),
 IOP("hjei",hicum2_model_hjei,IF_REAL,"hjei"),
 IOP("hjci",hicum2_model_hjci,IF_REAL,"hjci"),
 IOP("ibeis",hicum2_model_ibeis,IF_REAL,"ibeis"),
 IOP("mbei",hicum2_model_mbei,IF_REAL,"mbei"),
 IOP("ireis",hicum2_model_ireis,IF_REAL,"ireis"),
 IOP("mrei",hicum2_model_mrei,IF_REAL,"mrei"),
 IOP("ibeps",hicum2_model_ibeps,IF_REAL,"ibeps"),
 IOP("mbep",hicum2_model_mbep,IF_REAL,"mbep"),
 IOP("ireps",hicum2_model_ireps,IF_REAL,"ireps"),
 IOP("mrep",hicum2_model_mrep,IF_REAL,"mrep"),
 IOP("mcf",hicum2_model_mcf,IF_REAL,"mcf"),
 IOP("tbhrec",hicum2_model_tbhrec,IF_REAL,"tbhrec"),
 IOP("ibcis",hicum2_model_ibcis,IF_REAL,"ibcis"),
 IOP("mbci",hicum2_model_mbci,IF_REAL,"mbci"),
 IOP("ibcxs",hicum2_model_ibcxs,IF_REAL,"ibcxs"),
 IOP("mbcx",hicum2_model_mbcx,IF_REAL,"mbcx"),
 IOP("ibets",hicum2_model_ibets,IF_REAL,"ibets"),
 IOP("abet",hicum2_model_abet,IF_REAL,"abet"),
 IOP("tunode",hicum2_model_tunode,IF_INTEGER,"tunode"),
 IOP("favl",hicum2_model_favl,IF_REAL,"favl"),
 IOP("qavl",hicum2_model_qavl,IF_REAL,"qavl"),
 IOP("alfav",hicum2_model_alfav,IF_REAL,"alfav"),
 IOP("alqav",hicum2_model_alqav,IF_REAL,"alqav"),
 IOP("rbi0",hicum2_model_rbi0,IF_REAL,"rbi0"),
 IOP("rbx",hicum2_model_rbx,IF_REAL,"rbx"),
 IOP("fgeo",hicum2_model_fgeo,IF_REAL,"fgeo"),
 IOP("fdqr0",hicum2_model_fdqr0,IF_REAL,"fdqr0"),
 IOP("fcrbi",hicum2_model_fcrbi,IF_REAL,"fcrbi"),
 IOP("fqi",hicum2_model_fqi,IF_REAL,"fqi"),
 IOP("re",hicum2_model_re,IF_REAL,"re"),
 IOP("rcx",hicum2_model_rcx,IF_REAL,"rcx"),
 IOP("itss",hicum2_model_itss,IF_REAL,"itss"),
 IOP("msf",hicum2_model_msf,IF_REAL,"msf"),
 IOP("iscs",hicum2_model_iscs,IF_REAL,"iscs"),
 IOP("msc",hicum2_model_msc,IF_REAL,"msc"),
 IOP("tsf",hicum2_model_tsf,IF_REAL,"tsf"),
 IOP("rsu",hicum2_model_rsu,IF_REAL,"rsu"),
 IOP("csu",hicum2_model_csu,IF_REAL,"csu"),
 IOP("cjei0",hicum2_model_cjei0,IF_REAL,"cjei0"),
 IOP("vdei",hicum2_model_vdei,IF_REAL,"vdei"),
 IOP("zei",hicum2_model_zei,IF_REAL,"zei"),
 IOP("ajei",hicum2_model_ajei,IF_REAL,"ajei"),
 IOP("cjep0",hicum2_model_cjep0,IF_REAL,"cjep0"),
 IOP("vdep",hicum2_model_vdep,IF_REAL,"vdep"),
 IOP("zep",hicum2_model_zep,IF_REAL,"zep"),
 IOP("ajep",hicum2_model_ajep,IF_REAL,"ajep"),
 IOP("cjci0",hicum2_model_cjci0,IF_REAL,"cjci0"),
 IOP("vdci",hicum2_model_vdci,IF_REAL,"vdci"),
 IOP("zci",hicum2_model_zci,IF_REAL,"zci"),
 IOP("vptci",hicum2_model_vptci,IF_REAL,"vptci"),
 IOP("cjcx0",hicum2_model_cjcx0,IF_REAL,"cjcx0"),
 IOP("vdcx",hicum2_model_vdcx,IF_REAL,"vdcx"),
 IOP("zcx",hicum2_model_zcx,IF_REAL,"zcx"),
 IOP("vptcx",hicum2_model_vptcx,IF_REAL,"vptcx"),
 IOP("fbcpar",hicum2_model_fbcpar,IF_REAL,"fbcpar"),
 IOP("fbepar",hicum2_model_fbepar,IF_REAL,"fbepar"),
 IOP("cjs0",hicum2_model_cjs0,IF_REAL,"cjs0"),
 IOP("vds",hicum2_model_vds,IF_REAL,"vds"),
 IOP("zs",hicum2_model_zs,IF_REAL,"zs"),
 IOP("vpts",hicum2_model_vpts,IF_REAL,"vpts"),
 IOP("t0",hicum2_model_t0,IF_REAL,"t0"),
 IOP("dt0h",hicum2_model_dt0h,IF_REAL,"dt0h"),
 IOP("tbvl",hicum2_model_tbvl,IF_REAL,"tbvl"),
 IOP("tef0",hicum2_model_tef0,IF_REAL,"tef0"),
 IOP("gtfe",hicum2_model_gtfe,IF_REAL,"gtfe"),
 IOP("thcs",hicum2_model_thcs,IF_REAL,"thcs"),
 IOP("ahc",hicum2_model_ahc,IF_REAL,"ahc"),
 IOP("fthc",hicum2_model_fthc,IF_REAL,"fthc"),
 IOP("rci0",hicum2_model_rci0,IF_REAL,"rci0"),
 IOP("vlim",hicum2_model_vlim,IF_REAL,"vlim"),
 IOP("vces",hicum2_model_vces,IF_REAL,"vces"),
 IOP("vpt",hicum2_model_vpt,IF_REAL,"vpt"),
 IOP("tr",hicum2_model_tr,IF_REAL,"tr"),
 IOP("cbepar",hicum2_model_cbepar,IF_REAL,"cbepar"),
 IOP("cbcpar",hicum2_model_cbcpar,IF_REAL,"cbcpar"),
 IOP("alqf",hicum2_model_alqf,IF_REAL,"alqf"),
 IOP("alit",hicum2_model_alit,IF_REAL,"alit"),
 IOP("flnqs",hicum2_model_flnqs,IF_INTEGER,"flnqs"),
 IOP("kf",hicum2_model_kf,IF_REAL,"kf"),
 IOP("af",hicum2_model_af,IF_REAL,"af"),
 IOP("cfbe",hicum2_model_cfbe,IF_INTEGER,"cfbe"),
 IOP("latb",hicum2_model_latb,IF_REAL,"latb"),
 IOP("latl",hicum2_model_latl,IF_REAL,"latl"),
 IOP("vgb",hicum2_model_vgb,IF_REAL,"vgb"),
 IOP("alt0",hicum2_model_alt0,IF_REAL,"alt0"),
 IOP("kt0",hicum2_model_kt0,IF_REAL,"kt0"),
 IOP("zetaci",hicum2_model_zetaci,IF_REAL,"zetaci"),
 IOP("alvs",hicum2_model_alvs,IF_REAL,"alvs"),
 IOP("alces",hicum2_model_alces,IF_REAL,"alces"),
 IOP("zetarbi",hicum2_model_zetarbi,IF_REAL,"zetarbi"),
 IOP("zetarbx",hicum2_model_zetarbx,IF_REAL,"zetarbx"),
 IOP("zetarcx",hicum2_model_zetarcx,IF_REAL,"zetarcx"),
 IOP("zetare",hicum2_model_zetare,IF_REAL,"zetare"),
 IOP("zetacx",hicum2_model_zetacx,IF_REAL,"zetacx"),
 IOP("vge",hicum2_model_vge,IF_REAL,"vge"),
 IOP("vgc",hicum2_model_vgc,IF_REAL,"vgc"),
 IOP("vgs",hicum2_model_vgs,IF_REAL,"vgs"),
 IOP("f1vg",hicum2_model_f1vg,IF_REAL,"f1vg"),
 IOP("f2vg",hicum2_model_f2vg,IF_REAL,"f2vg"),
 IOP("zetact",hicum2_model_zetact,IF_REAL,"zetact"),
 IOP("zetabet",hicum2_model_zetabet,IF_REAL,"zetabet"),
 IOP("alb",hicum2_model_alb,IF_REAL,"alb"),
 IOP("flsh",hicum2_model_flsh,IF_INTEGER,"flsh"),
 IOP("rth",hicum2_model_rth,IF_REAL,"rth"),
 IOP("cth",hicum2_model_cth,IF_REAL,"cth"),
 IOP("flcomp",hicum2_model_flcomp,IF_REAL,"flcomp"),
 IOP("tnom",hicum2_model_tnom,IF_REAL,"tnom"),
 IOP("dt",hicum2_model_dt,IF_REAL,"dt")
};


char *hicum2names[] = { "c",
 "b",
 "e",
 "s",
 "tnode",
 "ci",
 "ei",
 "bp",
 "bi",
 "si",
 "xf1",
 "xf2",
 "xf3",
 "xf4",
 "n1",
 "n2"
};

int hicum2nSize = NUMELEMS(hicum2names);
int hicum2pTSize = NUMELEMS(hicum2pTable);
int hicum2mPTSize = NUMELEMS(hicum2mPTable);
int hicum2iSize = sizeof(hicum2instance);
int hicum2mSize = sizeof(hicum2model);
